pub struct Host {
    pub agent: String,
    pub platform: String,
    pub language: String,
    pub languages: Vec<String>,
    pub timezone: String,
    pub offset: f64,
    pub cores: f64,
    pub memory: f64,
    pub touch: f64,
    pub width: f64,
    pub height: f64,
    pub avail_width: f64,
    pub avail_height: f64,
    pub inner_width: f64,
    pub inner_height: f64,
    pub outer_width: f64,
    pub outer_height: f64,
    pub ratio: f64,
    pub depth: f64,
    pub vendor: String,
    pub renderer: String,
    pub origin: String,
    pub page: String,
    pub now: f64,
    pub elapsed: f64,
    pub seed: u64,
    pub document: String,
}

impl Default for Host {
    fn default() -> Self {
        Host {
            agent: String::new(),
            platform: String::new(),
            language: "en-US".to_string(),
            languages: vec!["en-US".to_string(), "en".to_string()],
            timezone: "Europe/Berlin".to_string(),
            offset: -120.0,
            cores: 8.0,
            memory: 8.0,
            touch: 0.0,
            width: 1512.0,
            height: 982.0,
            avail_width: 1512.0,
            avail_height: 945.0,
            inner_width: 1512.0,
            inner_height: 858.0,
            outer_width: 1512.0,
            outer_height: 945.0,
            ratio: 2.0,
            depth: 24.0,
            vendor: String::new(),
            renderer: String::new(),
            origin: "https://geo.captcha-delivery.com".to_string(),
            page: "/captcha/".to_string(),
            now: 1787961600000.0,
            elapsed: 812.5,
            seed: 0x9e3779b97f4a7c15,
            document: String::new(),
        }
    }
}
