[package]
name = "dd-fetch"
version = "0.1.0"
edition = "2024"

[dependencies]
wreq = { workspace = true }
wreq-util = { workspace = true }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time", "fs"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
base64 = "0.22"
futures-util = "0.3"

[[bin]]
name = "dd-fetch"
path = "src/main.rs"
