[package]
name = "dd-deob"
version = "0.1.0"
edition = "2024"

[dependencies]
oxc_allocator = "0.128.0"
oxc_parser = { version = "0.128.0", default-features = false }
oxc_ast = "0.128.0"
oxc_ast_visit = "0.128.0"
oxc_span = "0.128.0"
oxc_syntax = "0.128.0"
oxc_semantic = "0.128.0"
oxc_codegen = { version = "0.128.0", default-features = false }
rustc-hash = "2.1.2"
base64 = "0.22.1"
wasmprinter = "0.248.0"
mimalloc = "0.1"
serde_json = "1.0.149"
sha2 = "0.10"

[lib]
name = "dd_deob"
path = "src/lib.rs"

[[bin]]
name = "dd-deob"
path = "src/main.rs"

[[bin]]
name = "dd-pretty"
path = "src/bin/pretty.rs"

[[bin]]
name = "build-vm-db"
path = "src/bin/build_vm_db.rs"
